<!doctype html>
<html lang="es"><head><meta charset="utf-8"><style>
@page { margin: 18mm 18mm 16mm; } body { font-family: DejaVu Sans, sans-serif; color:#111; font-size:10.5pt; line-height:1.35; }
.brand,.periods,.review { width:100%; border-collapse:collapse; } .brand { margin-bottom:4mm; } .brand td { vertical-align:middle; } .brand-left { width:30%; } .brand-center { text-align:center; width:40%; } .brand-right { text-align:right; width:30%; }
.logo-hospital { width:34mm; } .logo-minsal { width:25mm; } .logo-trabajando { width:29mm; } h1 { text-align:center; font-size:14pt; margin:2mm 0 6mm; text-decoration:underline; }
.memo { text-align:right; font-weight:bold; margin-bottom:5mm; } .routing { margin-bottom:6mm; } .section { margin:0 0 5mm; page-break-inside:avoid; } .section-title { font-weight:bold; margin-bottom:1.5mm; }
.periods th,.periods td { border:1px solid #555; padding:2mm; text-align:left; } .review td { padding:1mm 0; } .footer { position:fixed; bottom:-8mm; left:0; right:0; text-align:center; font-size:7.5pt; color:#666; }
</style></head><body>
@php($asset = fn(string $path) => preg_replace('/\s+/', '', file_get_contents(resource_path('assets/reemplazos/'.$path))))
<table class="brand"><tr><td class="brand-left"><img class="logo-hospital" src="data:image/jpeg;base64,{{ $asset('logo-hospital.jpeg.b64') }}"></td><td class="brand-center"><img class="logo-trabajando" src="data:image/png;base64,{{ $asset('logo-trabajando.png.b64') }}"></td><td class="brand-right"><img class="logo-minsal" src="data:image/png;base64,{{ $asset('logo-minsal.png.b64') }}"></td></tr></table>
<div class="memo">MEMORANDUM N.º __________ /{{ \Carbon\CarbonImmutable::parse($snapshot['generado_at'])->year }}</div>
<h1>SOLICITUD DE REEMPLAZO DE PERSONAL</h1>
<div class="routing"><strong>A:</strong> {{ $snapshot['destinatario'] }}<br><strong>DE:</strong> {{ mb_strtoupper($snapshot['tramite']['creador'] ?? 'JEFATURA SOLICITANTE') }} · {{ mb_strtoupper($snapshot['tramite']['unidad']) }}</div>
<div class="section"><div class="section-title">1.- Antecedentes del funcionario reemplazado</div><p>{{ $snapshot['funcionario']['nombre'] }}, RUT {{ \App\Support\Rut\Rut::format($snapshot['funcionario']['rut']) }}.@if($snapshot['funcionario']['estamento']) Estamento: {{ $snapshot['funcionario']['estamento'] }}.@endif @if($snapshot['funcionario']['profesion']) Profesión: {{ $snapshot['funcionario']['profesion'] }}.@endif @if($snapshot['funcionario']['cargo']) Cargo o función: {{ $snapshot['funcionario']['cargo'] }}.@endif</p></div>
<div class="section"><div class="section-title">2.- Períodos de la solicitud</div><table class="periods"><tr><th>Período del funcionario reemplazado</th><th>Período del reemplazante</th></tr><tr><td>Desde: {{ \Carbon\CarbonImmutable::parse($snapshot['funcionario']['desde'])->format('d/m/Y') }}<br>Hasta: {{ \Carbon\CarbonImmutable::parse($snapshot['funcionario']['hasta'])->format('d/m/Y') }}</td><td>Desde: {{ \Carbon\CarbonImmutable::parse($snapshot['reemplazante']['desde'])->format('d/m/Y') }}<br>Hasta: {{ \Carbon\CarbonImmutable::parse($snapshot['reemplazante']['hasta'])->format('d/m/Y') }}</td></tr></table><p>{{ $snapshot['solicitud']['dias_cubiertos'] }} de {{ $snapshot['solicitud']['dias_totales'] }} días cubiertos; {{ $snapshot['solicitud']['dias_sin_cobertura'] }} días sin cobertura.</p></div>
<div class="section"><div class="section-title">3.- Tipo y justificación</div><p><strong>Tipo:</strong> {{ $snapshot['solicitud']['tipo'] }}</p><p>{{ $snapshot['solicitud']['justificacion'] }}</p></div>
<div class="section"><div class="section-title">4.- Reemplazante propuesto</div><p>{{ $snapshot['reemplazante']['nombre'] }}, RUT {{ \App\Support\Rut\Rut::format($snapshot['reemplazante']['rut']) }}. Unidad: {{ $snapshot['tramite']['unidad'] }}.</p></div>
<div class="section"><div class="section-title">5.- Revisión de Gestión de Personas</div><table class="review"><tr><td>Grado E.U.S.: <strong>{{ $snapshot['revision']['grado_eus'] }}°</strong></td></tr><tr><td>Clasificación de área: {{ $snapshot['revision']['clasificacion_area'] }}</td></tr><tr><td>Cumple normativa vigente: {{ $snapshot['revision']['cumple_normativa'] ? 'Sí' : 'No' }}</td></tr>@if($snapshot['revision']['observacion'])<tr><td>Observación: {{ $snapshot['revision']['observacion'] }}</td></tr>@endif</table></div>
<div class="section"><p>Espacio para tramitación y firmas institucionales externas.</p></div>
<div class="footer">Hospital de Illapel · Documento generado para posterior tramitación externa</div>
</body></html>
