<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold text-gray-800">{{ $persona->nombre_completo }}</h2></x-slot>
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded bg-green-50 p-3 text-green-800">{{ session('status') }}</div>@endif
        <section class="rounded-lg bg-white p-5 shadow-sm"><div class="flex flex-wrap justify-between gap-4"><div><p><strong>RUT:</strong> {{ \App\Support\Rut\Rut::format($persona->rut) }}</p><p><strong>Estado:</strong> {{ $persona->active ? 'Activa' : 'Inactiva' }}</p></div>@can('personas.gestionar')<div class="flex gap-2"><a class="rounded border px-4 py-2 text-sm" href="{{ route('personas.edit', $persona) }}">Editar</a><form method="POST" action="{{ route('personas.activo', $persona) }}">@csrf @method('PATCH')<x-secondary-button>{{ $persona->active ? 'Desactivar' : 'Activar' }}</x-secondary-button></form></div>@endcan</div></section>
        <section class="rounded-lg bg-white p-5 shadow-sm"><h3 class="text-lg font-semibold">Historial de vínculos</h3><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-2">Unidad</th><th class="p-2">Estamento / profesión</th><th class="p-2">Cargo</th><th class="p-2">Vigencia</th><th class="p-2">Estado</th></tr></thead><tbody>@forelse($persona->vinculos as $vinculo)<tr class="border-t"><td class="p-2">{{ $vinculo->unidad->nombre }}</td><td class="p-2">{{ $vinculo->estamento?->nombre ?? '—' }} / {{ $vinculo->profesion?->nombre ?? '—' }}</td><td class="p-2">{{ $vinculo->cargo_texto ?? '—' }}</td><td class="p-2">{{ $vinculo->start_date?->format('d-m-Y') ?? '—' }} a {{ $vinculo->end_date?->format('d-m-Y') ?? 'vigente' }}</td><td class="p-2">{{ $vinculo->status }}</td></tr>
            @can('personas.gestionar')<tr><td colspan="5" class="pb-3"><details><summary class="cursor-pointer text-sm text-blue-700">Editar o cerrar vínculo</summary><form method="POST" action="{{ route('personas.vinculos.update', [$persona, $vinculo]) }}" class="mt-2 grid gap-2 rounded bg-gray-50 p-3 md:grid-cols-4">@csrf @method('PUT')
                <select name="unidad_servicio_id" class="rounded border-gray-300">@foreach($unidades as $item)<option value="{{ $item->id }}" @selected($vinculo->unidad_servicio_id === $item->id)>{{ $item->nombre }}</option>@endforeach</select>
                <select name="estamento_id" class="rounded border-gray-300"><option value="">Sin estamento</option>@foreach($estamentos as $item)<option value="{{ $item->id }}" @selected($vinculo->estamento_id === $item->id)>{{ $item->nombre }}</option>@endforeach</select>
                <select name="profesion_id" class="rounded border-gray-300"><option value="">Sin profesión</option>@foreach($profesiones as $item)<option value="{{ $item->id }}" @selected($vinculo->profesion_id === $item->id)>{{ $item->nombre }}</option>@endforeach</select>
                <x-text-input name="cargo_texto" :value="$vinculo->cargo_texto"/><x-text-input type="date" name="start_date" :value="$vinculo->start_date?->format('Y-m-d')"/><x-text-input type="date" name="end_date" :value="$vinculo->end_date?->format('Y-m-d')"/>
                <select name="status" class="rounded border-gray-300">@foreach($estados as $estado)<option value="{{ $estado }}" @selected($vinculo->status === $estado)>{{ $estado }}</option>@endforeach</select><x-secondary-button>Guardar vínculo</x-secondary-button>
            </form></details></td></tr>@endcan
            @empty<tr><td colspan="5" class="p-3 text-gray-500">Sin vínculos.</td></tr>@endforelse</tbody></table></div></section>
        @can('personas.gestionar')<section class="rounded-lg bg-white p-5 shadow-sm"><h3 class="text-lg font-semibold">Agregar vínculo</h3><form method="POST" action="{{ route('personas.vinculos.store', $persona) }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf
            <select name="unidad_servicio_id" required class="rounded border-gray-300"><option value="">Unidad/Servicio</option>@foreach($unidades as $item)<option value="{{ $item->id }}">{{ $item->nombre }}</option>@endforeach</select>
            <select name="estamento_id" class="rounded border-gray-300"><option value="">Sin estamento</option>@foreach($estamentos as $item)<option value="{{ $item->id }}">{{ $item->nombre }}</option>@endforeach</select>
            <select name="profesion_id" class="rounded border-gray-300"><option value="">Sin profesión</option>@foreach($profesiones as $item)<option value="{{ $item->id }}">{{ $item->nombre }}</option>@endforeach</select>
            <x-text-input name="cargo_texto" placeholder="Cargo o función"/><x-text-input type="date" name="start_date"/><x-text-input type="date" name="end_date"/>
            <select name="status" required class="rounded border-gray-300">@foreach($estados as $estado)<option value="{{ $estado }}">{{ $estado }}</option>@endforeach</select><div class="md:col-span-2"><x-primary-button>Agregar vínculo</x-primary-button></div>
        </form><x-input-error :messages="$errors->all()" class="mt-3"/></section>@endcan
    </div></div>
</x-app-layout>
