@php($r = $tramite->reemplazo)
<section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print-card">
    <h3 class="text-lg font-semibold text-slate-900">Personas involucradas</h3>
    <div class="mt-4 grid gap-4 md:grid-cols-2">
        <article class="rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="text-xs font-semibold uppercase text-slate-500">Funcionario a reemplazar</p><p class="mt-2 font-semibold">{{ $r?->funcionario?->nombre_completo ?? 'No asociado' }}</p>@if($r?->funcionario)<p class="text-sm text-slate-600">{{ \App\Support\Rut\Rut::format($r->funcionario->rut) }}</p>@endif</article>
        <article class="rounded-lg border border-blue-100 bg-blue-50 p-4"><p class="text-xs font-semibold uppercase text-slate-500">Reemplazante propuesto</p><p class="mt-2 font-semibold">{{ $r?->reemplazante?->nombre_completo ?? 'Pendiente' }}</p>@if($r?->reemplazante)<p class="text-sm text-slate-600">{{ \App\Support\Rut\Rut::format($r->reemplazante->rut) }}</p>@endif<p class="mt-2 text-sm text-slate-600">{{ $r?->estamento?->nombre ?? '—' }} · {{ $r?->profesion?->nombre ?? $r?->cargo_texto ?? '—' }}</p></article>
    </div>
</section>
<section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print-card"><h3 class="text-lg font-semibold">Resumen del reemplazo</h3><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><p class="text-xs text-slate-500">Tipo y unidad</p><p>{{ $r?->tipoReemplazo?->nombre ?? 'Pendiente' }}</p><p class="text-sm text-slate-600">{{ $tramite->unidadServicio->nombre }}</p></div><div><p class="text-xs text-slate-500">Cargo o función</p><p>{{ $r?->cargo_texto ?? 'Pendiente' }}</p></div><div><p class="text-xs text-slate-500">Desde</p><p>{{ $r?->fecha_inicio?->format('d M. Y') ?? '—' }}</p></div><div><p class="text-xs text-slate-500">Hasta</p><p>{{ $r?->fecha_termino?->format('d M. Y') ?? '—' }}</p></div></div><div class="mt-5 border-t pt-4"><p class="text-xs font-semibold uppercase text-slate-500">Justificación</p><p class="mt-2 whitespace-pre-line text-slate-700">{{ $r?->justificacion ?: 'Pendiente de completar.' }}</p></div></section>
