@php($r = $tramite->reemplazo)
@php($revision = $tramite->revisionReemplazo)
@php($devolucion = $tramite->historial->where('action_code', 'DEVOLVER_CORRECCION')->last())
@if($tramite->estadoTramite->codigo === 'DEVUELTA_CORRECCION' && $devolucion)<div class="rounded border border-red-300 bg-red-50 p-4"><strong>Devuelta para corrección:</strong> {{ $devolucion->observation }}</div>@endif
<section class="grid gap-5 rounded-lg bg-white p-5 shadow-sm md:grid-cols-2"><div><h3 class="font-semibold">Solicitud</h3><p>Tipo: {{ $r?->tipoReemplazo?->nombre ?? 'Pendiente' }}</p><p>Funcionario: {{ $r?->funcionario?->nombre_completo ?? 'No asociado' }}</p><p>Justificación: {{ $r?->justificacion ?: 'Pendiente' }}</p></div><div><h3 class="font-semibold">Reemplazante</h3><p>{{ $r?->reemplazante?->nombre_completo ?? 'Pendiente' }}</p><p>RUT: {{ $r?->reemplazante ? \App\Support\Rut\Rut::format($r->reemplazante->rut) : '—' }}</p><p>{{ $r?->estamento?->nombre ?? '—' }} / {{ $r?->profesion?->nombre ?? '—' }}</p><p>Cargo: {{ $r?->cargo_texto ?? '—' }}</p><p>Fechas: {{ $r?->fecha_inicio?->format('d-m-Y') ?? '—' }} a {{ $r?->fecha_termino?->format('d-m-Y') ?? '—' }}</p><p>Unidad: {{ $tramite->unidadServicio->nombre }}</p></div></section>
<section class="rounded-lg bg-white p-5 shadow-sm"><h3 class="font-semibold">Gestión de Personas</h3><p>Grado E.U.S.: {{ $revision?->gradoEus?->grado ?? 'Pendiente de catálogo oficial' }}</p><p>Clasificación: {{ $revision?->clasificacionArea?->nombre ?? 'Pendiente' }}</p><p>Cumple normativa: {{ $revision?->cumple_normativa === null ? 'Pendiente' : ($revision->cumple_normativa ? 'Sí' : 'No') }}</p><p>Completado por: {{ $revision?->completadoPor?->name ?? 'Pendiente' }}</p>
@can('reemplazos.revisar_personal')@if($tramite->estadoTramite->codigo === 'ENVIADA_GESTION_PERSONAS')<form method="POST" action="{{ route('reemplazos.review.start', $tramite) }}" class="mt-3">@csrf<x-primary-button>Iniciar revisión</x-primary-button></form>@endif
@if($tramite->estadoTramite->codigo === 'EN_REVISION')<form method="POST" action="{{ route('reemplazos.review.save', $tramite) }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf @method('PUT')@if($grados->isEmpty())<p class="rounded bg-amber-50 p-3 md:col-span-3">Catálogo de grados E.U.S. pendiente de validación por RRHH.</p>@else<select name="grado_eus_id" class="rounded border-gray-300"><option value="">Grado E.U.S.</option>@foreach($grados as $grado)<option value="{{ $grado->id }}">{{ $grado->grado }}</option>@endforeach</select>@endif<select name="clasificacion_area_id" class="rounded border-gray-300"><option value="">Clasificación</option>@foreach($clasificaciones as $item)<option value="{{ $item->id }}" @selected($revision?->clasificacion_area_id === $item->id)>{{ $item->nombre }}</option>@endforeach</select><select name="cumple_normativa" class="rounded border-gray-300"><option value="">Cumple normativa</option><option value="1" @selected($revision?->cumple_normativa === true)>Sí</option><option value="0" @selected($revision?->cumple_normativa === false)>No</option></select><x-secondary-button>Guardar punto 4</x-secondary-button></form><div class="mt-4 flex flex-wrap gap-3"><form method="POST" action="{{ route('reemplazos.return', $tramite) }}" class="flex gap-2">@csrf<textarea name="observation" required placeholder="Motivo de devolución" class="rounded border-gray-300"></textarea><x-secondary-button>Devolver</x-secondary-button></form><form method="POST" action="{{ route('reemplazos.review.complete', $tramite) }}">@csrf<x-primary-button>Completar revisión</x-primary-button></form></div>@endif @endcan
@can('reemplazos.crear')@if(in_array($tramite->estadoTramite->codigo, ['BORRADOR','DEVUELTA_CORRECCION'], true))<a class="mt-4 inline-block text-blue-700" href="{{ route('reemplazos.edit', $tramite) }}">Editar sección Jefatura</a>@endif @endcan @if($tramite->estadoTramite->codigo === 'LISTA_GENERAR_DOCUMENTO')<p class="mt-4 rounded bg-amber-50 p-3 text-amber-900">Plantilla institucional de Solicitud de Reemplazo pendiente de validación por RRHH.</p>@endif</section>
