<x-app-layout>
    <x-slot name="header"><h2 class="text-xl font-semibold">Documento institucional · {{ $tramite->codigo }}</h2><p class="text-sm text-slate-500">{{ $tramite->unidadOrganizacional->nombre }} · {{ $tramite->estadoTramite->nombre }}</p></x-slot>
    <div class="py-10"><div class="mx-auto max-w-5xl space-y-5 px-4">
        @if(session('status'))<div class="rounded bg-green-50 p-3 text-green-800">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded bg-red-50 p-3 text-red-800">{{ $errors->first() }}</div>@endif
        <div class="grid gap-5 md:grid-cols-2"><section class="rounded-xl bg-white p-6 shadow"><h3 class="font-semibold">Funcionario reemplazado</h3><p class="mt-2">{{ $tramite->reemplazo->funcionario->nombre_completo }} · {{ $tramite->reemplazo->funcionario->rut }}</p><p>{{ $tramite->reemplazo->fecha_funcionario_desde->format('d/m/Y') }} al {{ $tramite->reemplazo->fecha_funcionario_hasta->format('d/m/Y') }}</p></section><section class="rounded-xl bg-white p-6 shadow"><h3 class="font-semibold">Reemplazante</h3><p class="mt-2">{{ $tramite->reemplazo->reemplazante->nombre_completo }} · {{ $tramite->reemplazo->reemplazante->rut }}</p><p>{{ $tramite->reemplazo->fecha_reemplazante_desde->format('d/m/Y') }} al {{ $tramite->reemplazo->fecha_reemplazante_hasta->format('d/m/Y') }}</p></section></div>
        <section class="rounded-xl bg-white p-6 shadow"><h3 class="font-semibold">Documento generado</h3>@if($documento=$tramite->documentosGenerados->firstWhere('status','VIGENTE'))<p class="mt-3">Solicitud de Reemplazo · Versión {{ $documento->version }}</p><p class="text-sm text-slate-600">Generado: {{ $documento->generated_at->format('d/m/Y H:i') }} · Por: {{ $documento->generadoPor->name }}</p>@can('generar-documento-reemplazo',$tramite)<a href="{{ route('reemplazos.documentos.download',[$tramite,$documento]) }}" class="mt-4 inline-block rounded bg-indigo-700 px-4 py-2 text-sm font-semibold text-white">Descargar PDF</a>@endcan @else @can('generar-documento-reemplazo',$tramite)<p class="mt-2 text-sm text-slate-600">Se generará el documento institucional con los antecedentes actualmente aprobados.</p><form method="POST" action="{{ route('reemplazos.documentos.store',$tramite) }}" class="mt-4">@csrf<x-primary-button>Generar documento</x-primary-button></form>@endcan @endif</section>
    </div></div>
</x-app-layout>
