<x-app-layout>
    <x-slot name="header"><div><h2 class="text-xl font-semibold text-slate-800">Bandeja de solicitudes</h2><p class="mt-1 text-sm text-slate-600">Solicitudes de Reemplazo recibidas para revisión administrativa.</p></div></x-slot>
    @php($groups = [['Todas', null], ['Nuevas por revisar', 'nuevas_por_revisar'], ['En revisión', 'en_revision_gp'], ['Devueltas esperando corrección', 'devueltas_esperando_correccion'], ['Listas para generar documento', 'listas_generar_documento'], ['Documento generado', 'documento_generado'], ['Formalizadas', 'formalizados']])
    @php($activeGroup = request('estado_grupo'))
    <div class="py-10"><div class="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8">
        <nav class="flex flex-wrap gap-2" aria-label="Estado de las solicitudes">@foreach($groups as [$label, $value])<a href="{{ route('gestion-personas.bandeja', array_filter(['estado_grupo' => $value])) }}" @class(['rounded-full px-3 py-2 text-sm font-medium transition focus:outline-none focus:ring-2 focus:ring-indigo-500', 'bg-indigo-700 text-white' => $activeGroup === $value || (! $activeGroup && ! $value), 'bg-white text-slate-700 shadow-sm ring-1 ring-slate-200 hover:bg-slate-50' => ! ($activeGroup === $value || (! $activeGroup && ! $value))])>{{ $label }}</a>@endforeach</nav>
        <form method="GET" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-[minmax(0,1fr)_auto]"><input type="hidden" name="estado_grupo" value="{{ $activeGroup }}"><x-text-input name="codigo" :value="request('codigo')" placeholder="Buscar por código, RUT o funcionario" aria-label="Buscar por código, RUT o funcionario" /><div class="flex gap-2"><x-primary-button>Buscar</x-primary-button><a href="{{ route('gestion-personas.bandeja', array_filter(['estado_grupo' => $activeGroup])) }}" class="rounded-md px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100">Limpiar</a></div></form>
        <p class="text-sm text-slate-600">{{ $tramites->total() }} {{ $tramites->total() === 1 ? 'solicitud' : 'solicitudes' }}</p>
        <section class="space-y-3" aria-label="Solicitudes de Reemplazo">@forelse($tramites as $tramite)@php($state = $tramite->estadoTramite->codigo)@php($wasReturned = $tramite->historial->contains('action_code', 'DEVOLVER_CORRECCION'))@php($reviewer = $tramite->historial->where('action_code', 'INICIAR_REVISION')->last()?->usuario)<article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('tramites.show', $tramite) }}" class="font-semibold text-slate-900 hover:text-indigo-700">{{ $tramite->codigo }}</a><p class="mt-1 text-sm text-slate-600">{{ $tramite->tipoTramite->nombre }} · {{ $tramite->unidadServicio->nombre }}</p><p class="mt-1 text-sm text-slate-600">Jefatura creadora: {{ $tramite->creador?->name ?? 'Usuario no disponible' }}</p><p class="mt-1 text-sm text-slate-500">{{ $tramite->submitted_at ? 'Recibida '.$tramite->submitted_at->format('d-m-Y H:i') : 'Actualizada '.$tramite->updated_at->format('d-m-Y H:i') }}</p>@if($state === 'EN_REVISION' && $reviewer)<p class="mt-1 text-sm text-indigo-700">En revisión por {{ $reviewer->name }}</p>@endif</div><x-status-badge :estado="$tramite->estadoTramite" /></div><div class="mt-4 flex flex-wrap gap-3">@if($state === 'ENVIADA_GESTION_PERSONAS')<form method="POST" action="{{ route('reemplazos.review.start', $tramite) }}">@csrf<x-primary-button>{{ $wasReturned ? 'Revisar corrección' : 'Iniciar revisión' }}</x-primary-button></form>@elseif($state === 'EN_REVISION')<a href="{{ route('reemplazos.review.show', $tramite) }}" class="rounded-md bg-indigo-700 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-800">Continuar revisión</a>@else<a href="{{ route('tramites.show', $tramite) }}" class="text-sm font-semibold text-indigo-700 hover:text-indigo-900">Ver detalle</a>@endif</div></article>@empty<article class="rounded-xl border border-slate-200 bg-white p-8 text-center shadow-sm"><p class="font-medium text-slate-800">No se encontraron solicitudes en esta bandeja.</p><p class="mt-1 text-sm text-slate-600">Prueba con otro filtro o término de búsqueda.</p></article>@endforelse</section>
        {{ $tramites->links() }}
    </div></div>
</x-app-layout>
