<x-app-layout><x-slot name="header"><h2 class="text-xl font-semibold">{{ $vinculo ? 'Editar vínculo laboral' : 'Registrar vínculo laboral' }}</h2></x-slot><div class="py-10">
@if($calidades->isEmpty())<div class="mx-auto max-w-3xl rounded bg-amber-50 p-4">Debe <a class="underline" href="{{ route('admin.calidades.index') }}">configurar calidades contractuales</a> antes de registrar dotación.</div>@else
<form method="POST" action="{{ $vinculo ? route('admin.dotacion.update',$vinculo) : route('admin.dotacion.store') }}" class="mx-auto grid max-w-3xl gap-4 rounded bg-white p-6 shadow md:grid-cols-2">@csrf @if($vinculo)@method('PUT')@endif
<label>Persona<select name="persona_id" class="mt-1 w-full rounded border-gray-300" required>@foreach($personas as $p)<option value="{{ $p->id }}" @selected(old('persona_id',$vinculo?->persona_id)==$p->id)>{{ $p->nombre_completo }} · {{ $p->rut }}</option>@endforeach</select></label>
<label>Unidad<select name="unidad_organizacional_id" class="mt-1 w-full rounded border-gray-300" required>@foreach($unidades as $u)<option value="{{ $u['id'] }}" @selected(old('unidad_organizacional_id',$vinculo?->unidad_organizacional_id)==$u['id'])>{{ $u['ruta'] }}</option>@endforeach</select></label>
<label>Estamento<select name="estamento_id" class="mt-1 w-full rounded border-gray-300" required>@foreach($estamentos as $e)<option value="{{ $e->id }}" @selected(old('estamento_id',$vinculo?->estamento_id)==$e->id)>{{ $e->nombre }}</option>@endforeach</select></label>
<label>Profesión<select name="profesion_id" class="mt-1 w-full rounded border-gray-300"><option value="">Sin profesión</option>@foreach($profesiones as $p)<option value="{{ $p->id }}" @selected(old('profesion_id',$vinculo?->profesion_id)==$p->id)>{{ $p->nombre }}</option>@endforeach</select></label>
<label>Calidad contractual<select name="calidad_contractual_id" class="mt-1 w-full rounded border-gray-300" required>@foreach($calidades as $c)<option value="{{ $c->id }}" @selected(old('calidad_contractual_id',$vinculo?->calidad_contractual_id)==$c->id)>{{ $c->nombre }}</option>@endforeach</select></label>
<label>Cargo o función<x-text-input class="mt-1 w-full" name="cargo_funcion" value="{{ old('cargo_funcion',$vinculo?->cargo_funcion) }}" required/></label><label>Grado E.U.S.<x-text-input type="number" min="1" max="99" class="mt-1 w-full" name="grado_eus" value="{{ old('grado_eus',$vinculo?->grado_eus) }}"/></label>
<label>Desde<x-text-input type="date" class="mt-1 w-full" name="vigente_desde" value="{{ old('vigente_desde',$vinculo?->vigente_desde?->toDateString()) }}" required/></label><label>Hasta<x-text-input type="date" class="mt-1 w-full" name="vigente_hasta" value="{{ old('vigente_hasta',$vinculo?->vigente_hasta?->toDateString()) }}"/></label>
<label>Origen<select name="origen" class="mt-1 w-full rounded border-gray-300" required>@foreach($origenes as $o)<option value="{{ $o->value }}" @selected(old('origen',$vinculo?->origen?->value ?? 'MANUAL')===$o->value)>{{ $o->etiqueta() }}</option>@endforeach</select></label>
<label class="md:col-span-2">Observación<textarea name="observacion" class="mt-1 w-full rounded border-gray-300">{{ old('observacion',$vinculo?->observacion) }}</textarea></label><div class="md:col-span-2"><x-primary-button>Guardar</x-primary-button></div>
</form>@endif</div></x-app-layout>
