<p class="text-sm text-slate-600">{{ $tramites->total() }} {{ $tramites->total() === 1 ? 'resultado' : 'resultados' }}</p>
<div class="hidden overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm md:block"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-600"><tr><th class="p-4">Código</th><th class="p-4">Trámite</th><th class="p-4">Unidad</th><th class="p-4">Estado</th><th class="p-4">Última actualización</th><th class="p-4"><span class="sr-only">Acción</span></th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($tramites as $tramite)
    @php($code = $tramite->tipoTramite->codigo)
    @php($state = $tramite->estadoTramite->codigo)
    @php($editable = in_array($state, ['BORRADOR', 'DEVUELTA_CORRECCION'], true))
    @php($action = $state === 'BORRADOR' ? 'Continuar' : ($state === 'DEVUELTA_CORRECCION' ? 'Corregir' : (in_array($state, ['PLANILLA_DISPONIBLE', 'EN_REVISION_JEFATURA'], true) ? 'Revisar' : ($state === 'FORMALIZADA' ? 'Ver resultado' : 'Ver detalle'))))
    @php($url = $editable && $code === 'REEMPLAZO' ? route('reemplazos.edit', $tramite) : ($editable && $code === 'HORAS_EXTRAORDINARIAS' && $state === 'BORRADOR' ? route('horas-extra.edit', $tramite) : route('tramites.show', $tramite)))
    <tr><td class="p-4 font-medium text-slate-900"><a class="hover:text-indigo-700" href="{{ $url }}">{{ $tramite->codigo }}</a></td><td class="p-4"><p class="font-medium text-slate-800">{{ $tramite->tipoTramite->nombre }}</p>@if($code === 'REEMPLAZO')<p class="mt-1 text-slate-600">{{ $tramite->reemplazo?->funcionario?->nombre_completo ?? 'Funcionario no informado' }}</p><p class="text-slate-500">{{ $tramite->reemplazo?->fecha_inicio?->format('d M. Y') ?? 'Período no informado' }}{{ $tramite->reemplazo?->fecha_termino ? ' – '.$tramite->reemplazo->fecha_termino->format('d M. Y') : '' }}</p>@else<p class="mt-1 text-slate-600">{{ $tramite->horasExtra?->period_start?->translatedFormat('F Y') ?? 'Período no informado' }}</p><p class="text-slate-500">{{ $tramite->horasExtra?->funcionarios->count() ?? 0 }} funcionarios</p>@endif</td><td class="p-4 text-slate-600">{{ $tramite->unidadServicio->nombre }}</td><td class="p-4"><x-status-badge :estado="$tramite->estadoTramite" /></td><td class="p-4 text-slate-600">{{ $tramite->updated_at->format('d-m-Y H:i') }}</td><td class="p-4 text-right"><a class="font-semibold text-indigo-700 hover:text-indigo-900" href="{{ $url }}">{{ $action }}</a></td></tr>
@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No encontramos trámites con los filtros seleccionados. <a href="{{ route('tramites.index') }}" class="font-semibold text-indigo-700">Limpiar filtros</a></td></tr>@endforelse
</tbody></table></div>
<div class="space-y-3 md:hidden">@forelse($tramites as $tramite) @php($state = $tramite->estadoTramite->codigo) @php($action = $state === 'BORRADOR' ? 'Continuar' : ($state === 'DEVUELTA_CORRECCION' ? 'Corregir' : (in_array($state, ['PLANILLA_DISPONIBLE', 'EN_REVISION_JEFATURA'], true) ? 'Revisar' : ($state === 'FORMALIZADA' ? 'Ver resultado' : 'Ver detalle')))) @php($url = $state === 'DEVUELTA_CORRECCION' && $tramite->tipoTramite->codigo === 'REEMPLAZO' ? route('reemplazos.edit', $tramite) : ($state === 'BORRADOR' && $tramite->tipoTramite->codigo === 'REEMPLAZO' ? route('reemplazos.edit', $tramite) : ($state === 'BORRADOR' && $tramite->tipoTramite->codigo === 'HORAS_EXTRAORDINARIAS' ? route('horas-extra.edit', $tramite) : route('tramites.show', $tramite))))<article class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex justify-between gap-3"><p class="font-semibold text-slate-900">{{ $tramite->codigo }}</p><x-status-badge :estado="$tramite->estadoTramite" /></div><p class="mt-3 font-medium text-slate-800">{{ $tramite->tipoTramite->nombre }}</p><p class="mt-1 text-sm text-slate-600">{{ $tramite->unidadServicio->nombre }}</p><p class="mt-3 text-sm text-slate-500">Actualizado {{ $tramite->updated_at->format('d-m-Y H:i') }}</p><a class="mt-4 inline-block font-semibold text-indigo-700" href="{{ $url }}">{{ $action }}</a></article>@empty<article class="rounded-xl border border-slate-200 bg-white p-6 text-center text-slate-500">No encontramos trámites con los filtros seleccionados. <a href="{{ route('tramites.index') }}" class="font-semibold text-indigo-700">Limpiar filtros</a></article>@endforelse</div>
{{ $tramites->links() }}
