<x-app-layout><div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8"><x-flash-toast />
@if($tramite->tipoTramite->codigo === 'REEMPLAZO')
@php($estado = str_replace('Gestion Personas', 'a Gestión de Personas', $tramite->estadoTramite->nombre))
<header class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print-card"><p class="text-sm text-slate-500">Mis trámites / Solicitud de Reemplazo</p><div class="mt-3 flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-semibold text-slate-900">Solicitud de Reemplazo</h1><p class="font-mono text-sm text-slate-600">{{ $tramite->codigo }}</p><p class="mt-2 text-sm text-slate-600">{{ $tramite->unidadServicio->nombre }} · Creada por {{ $tramite->creador->name }} · {{ $tramite->created_at->format('d-m-Y H:i') }}</p></div><span class="h-fit rounded-full bg-blue-100 px-3 py-1 text-sm font-medium text-blue-800">{{ $estado }}</span></div></header>
<section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm print-card"><ol class="grid gap-3 text-sm sm:grid-cols-5">@foreach(['Solicitud creada','Gestión de Personas','Documento generado','DocDigital','Formalizada'] as $etapa)<li class="flex items-center gap-2 {{ $loop->first ? 'font-semibold text-blue-800' : 'text-slate-400' }}"><span class="grid h-6 w-6 place-items-center rounded-full border border-current">{{ $loop->iteration }}</span>{{ $etapa }}</li>@endforeach</ol></section>
<div class="grid grid-cols-1 items-start gap-6 lg:grid-cols-12"><main class="space-y-6 lg:col-span-8">@include('reemplazos._detail')
<section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print-card"><h3 class="text-lg font-semibold">Documentos del trámite</h3><div class="mt-4 space-y-3">@forelse($tramite->adjuntos as $adjunto)<article class="flex flex-wrap justify-between gap-3 rounded-lg border p-4"><div><p class="font-medium">[{{ strtoupper(pathinfo($adjunto->original_name, PATHINFO_EXTENSION)) }}] {{ $adjunto->original_name }}</p><p class="text-sm text-slate-600">{{ $adjunto->tipoDocumento?->nombre ?? 'Sin tipo' }} · Versión {{ $adjunto->version }} · {{ number_format($adjunto->size_bytes / 1024, 1) }} KB</p><p class="text-xs text-slate-500">Cargado por {{ $adjunto->cargadoPor->name }} · {{ $adjunto->created_at->format('d-m-Y H:i') }}</p></div>@can('tramites.adjuntos.descargar')<a class="text-sm font-medium text-blue-700" href="{{ route('tramites.adjuntos.download',[$tramite,$adjunto]) }}">Descargar</a>@endcan</article>@empty<p class="text-sm text-slate-500">Aún no hay documentos adjuntos.</p>@endforelse</div></section>
<section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm print-card"><h3 class="text-lg font-semibold">Historial del trámite</h3><ol class="mt-4 space-y-4">@foreach($tramite->historial as $evento)<li class="border-l-2 border-blue-200 pl-4"><p class="font-medium">{{ ['TRAMITE_CREADO'=>'Solicitud creada','ADJUNTO_CARGADO'=>'Documento adjuntado','ENVIAR_A_GESTION_PERSONAS'=>'Solicitud enviada a Gestión de Personas'][$evento->action_code] ?? str_replace('_',' ',ucwords(strtolower($evento->action_code),'_')) }}</p><p class="text-sm text-slate-600">{{ $evento->estadoOrigen?->nombre ?? 'Inicio' }} → {{ $evento->estadoDestino?->nombre ?? '—' }} · {{ $evento->usuario?->name ?? 'Sistema' }} · {{ $evento->occurred_at->format('d-m-Y H:i') }}</p>@if($evento->observation)<p class="mt-1 text-sm">{{ $evento->observation }}</p>@endif</li>@endforeach</ol></section></main>
<aside class="space-y-6 lg:col-span-4"><section class="rounded-xl border border-blue-100 bg-blue-50 p-5 shadow-sm"><h3 class="font-semibold">Estado actual</h3><p class="mt-2 font-medium">{{ $estado }}</p><p class="mt-1 text-sm text-slate-600">Revise los antecedentes y acciones disponibles para esta etapa.</p>@can('reemplazos.crear')@if(in_array($tramite->estadoTramite->codigo,['BORRADOR','DEVUELTA_CORRECCION'],true))<a class="mt-4 inline-block text-sm font-medium text-blue-700" href="{{ route('reemplazos.edit',$tramite) }}">Editar solicitud</a>@endif @endcan</section>
<section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-semibold">Gestión de Personas</h3>@php($revision=$tramite->revisionReemplazo)<dl class="mt-3 space-y-2 text-sm"><div><dt class="text-slate-500">Grado E.U.S.</dt><dd>{{ $revision?->gradoEus?->grado ?? ($revision ? 'Pendiente de configuración' : 'Pendiente') }}</dd></div><div><dt class="text-slate-500">Clasificación</dt><dd>{{ $revision?->clasificacionArea?->nombre ?? 'Pendiente' }}</dd></div><div><dt class="text-slate-500">Normativa</dt><dd>{{ $revision?->cumple_normativa === null ? 'Pendiente' : ($revision->cumple_normativa ? 'Sí' : 'No') }}</dd></div></dl>@can('reemplazos.revisar_personal')@if($tramite->estadoTramite->codigo==='ENVIADA_GESTION_PERSONAS')<form method="POST" action="{{ route('reemplazos.review.start',$tramite) }}" class="mt-4">@csrf<x-primary-button>Iniciar revisión</x-primary-button></form>@endif @endcan</section>@include('tramites._docdigital')</aside></div>
@else <section class="rounded-xl bg-white p-6 shadow-sm">@include('horas-extra._detail')</section>@endif
</div></div></x-app-layout>
