<x-app-layout><x-slot name="header"><h2 class="text-xl font-semibold">{{ $unidad ? 'Editar unidad organizacional' : 'Crear unidad organizacional' }}</h2></x-slot><div class="py-10"><form method="POST" action="{{ $unidad ? route('admin.estructura.update', $unidad) : route('admin.estructura.store') }}" class="mx-auto max-w-3xl space-y-4 rounded-xl bg-white p-6 shadow-sm">@csrf @if($unidad) @method('PUT') @endif
    <div><x-input-label for="codigo" value="Código estable"/><x-text-input id="codigo" name="codigo" class="mt-1 w-full" value="{{ old('codigo', $unidad?->codigo) }}"/><x-input-error :messages="$errors->get('codigo')"/></div>
    <div><x-input-label for="nombre" value="Nombre"/><x-text-input id="nombre" name="nombre" class="mt-1 w-full" value="{{ old('nombre', $unidad?->nombre) }}"/><x-input-error :messages="$errors->get('nombre')"/></div>
    <div><x-input-label for="sigla" value="Sigla"/><x-text-input id="sigla" name="sigla" class="mt-1 w-full" value="{{ old('sigla', $unidad?->sigla) }}"/></div>
    <div><x-input-label for="tipo_unidad_organizacional_id" value="Tipo"/><select id="tipo_unidad_organizacional_id" name="tipo_unidad_organizacional_id" class="mt-1 w-full rounded border-gray-300"><option value="">Seleccione</option>@foreach($tipos as $tipo)<option value="{{ $tipo->id }}" @selected(old('tipo_unidad_organizacional_id', $unidad?->tipo_unidad_organizacional_id)==$tipo->id)>{{ $tipo->nombre }}</option>@endforeach</select><x-input-error :messages="$errors->get('tipo_unidad_organizacional_id')"/></div>
    <div><x-input-label for="parent_id" value="Unidad superior"/><select id="parent_id" name="parent_id" class="mt-1 w-full rounded border-gray-300"><option value="">Nodo raíz</option>@foreach($padres as $padre)<option value="{{ $padre->id }}" @selected(old('parent_id', $parentId)==$padre->id)>{{ $padre->nombre }} ({{ $padre->codigo }})</option>@endforeach</select><x-input-error :messages="$errors->get('parent_id')"/></div>
    <div><x-input-label for="orden" value="Orden"/><x-text-input id="orden" type="number" min="0" name="orden" value="{{ old('orden', $unidad?->orden ?? 0) }}"/><x-input-error :messages="$errors->get('orden')"/></div>
    <div><x-input-label for="descripcion" value="Descripción"/><textarea id="descripcion" name="descripcion" class="mt-1 w-full rounded border-gray-300">{{ old('descripcion', $unidad?->descripcion) }}</textarea></div>
    <label class="flex gap-2"><input type="checkbox" name="activo" value="1" @checked(old('activo', $unidad?->activo ?? true))>Activo</label><label class="flex gap-2"><input type="checkbox" name="participa_en_aprobacion" value="1" @checked(old('participa_en_aprobacion', $unidad?->participa_en_aprobacion ?? false))>Participa en aprobación futura</label>
    <div class="flex gap-3"><x-primary-button>Guardar</x-primary-button><a href="{{ route('admin.estructura.index') }}">Cancelar</a></div>
</form></div></x-app-layout>
