<x-app-layout>
<div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8"><x-flash-toast />
<header class="rounded-xl border bg-white p-6 shadow-sm"><p class="text-sm text-slate-500">Ausencia reemplazable</p><div class="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-semibold">{{ $ausencia->funcionario?->nombre_completo ?? 'Funcionario pendiente' }}</h1><p class="text-slate-600">{{ $ausencia->unidad->nombre }} · {{ $ausencia->tipoReemplazo?->nombre ?? 'Motivo pendiente' }}</p><p class="mt-2">{{ $ausencia->fecha_inicio?->format('d-m-Y') ?? '—' }} al {{ $ausencia->fecha_termino?->format('d-m-Y') ?? '—' }} · {{ $resumen['total_dias'] }} días calendario</p></div><span class="rounded-full bg-indigo-100 px-3 py-1 text-sm font-semibold text-indigo-800">{{ $resumen['estado'] }}</span></div></header>
<section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Días documentados'=>$resumen['dias_documentados'],'Días en trámite'=>$resumen['dias_en_tramite'],'Días disponibles'=>$resumen['dias_disponibles'],'Porcentaje asignado'=>$resumen['porcentaje'].'%'] as $label=>$value)<article class="rounded-xl border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-2xl font-semibold">{{ $value }}</p></article>@endforeach</section>
<section class="rounded-xl border bg-white p-6 shadow-sm"><h2 class="font-semibold">Progreso de cobertura</h2><div class="mt-3 h-4 overflow-hidden rounded-full bg-slate-200"><div class="h-full bg-emerald-600" style="width: {{ min(100,$resumen['porcentaje']) }}%"></div></div><h3 class="mt-5 text-sm font-semibold">Periodos disponibles</h3><div class="mt-2 flex flex-wrap gap-2">@forelse($resumen['intervalos_disponibles'] as $intervalo)<span class="rounded bg-slate-100 px-3 py-2 text-sm">{{ $intervalo['inicio']->format('d-m-Y') }} al {{ $intervalo['termino']->format('d-m-Y') }} · {{ $intervalo['dias'] }} días</span>@empty<span class="text-sm text-emerald-700">No quedan días disponibles.</span>@endforelse</div></section>
<section class="rounded-xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><h2 class="text-lg font-semibold">Coberturas asociadas</h2>@if(!$ausencia->closed_at && $resumen['dias_disponibles'] > 0 && auth()->user()->can('reemplazos.crear'))<form method="POST" action="{{ route('reemplazos.absences.coverages.store',$ausencia) }}">@csrf<button class="rounded bg-indigo-700 px-4 py-2 text-sm font-semibold text-white">+ Agregar otra cobertura</button></form>@endif</div><div class="mt-4 space-y-3">@foreach($ausencia->coberturas as $index=>$coverage)<article class="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p class="font-semibold">Cobertura {{ $index+1 }} de {{ $ausencia->coberturas->count() }} · {{ $coverage->reemplazante?->nombre_completo ?? 'Reemplazante pendiente' }}</p><p class="text-sm text-slate-600">{{ $coverage->fecha_inicio?->format('d-m-Y') ?? '—' }} al {{ $coverage->fecha_termino?->format('d-m-Y') ?? '—' }} · {{ $coverage->dias_calendario }} días · {{ $coverage->tramite->estadoTramite->nombre }}</p></div><a class="font-semibold text-indigo-700" href="{{ in_array($coverage->tramite->estadoTramite->codigo,['BORRADOR','DEVUELTA_CORRECCION'],true) ? route('reemplazos.edit',$coverage->tramite) : route('tramites.show',$coverage->tramite) }}">{{ $coverage->tramite->codigo }}</a></article>@endforeach</div></section>
@if(!$ausencia->closed_at && auth()->user()->can('reemplazos.crear'))<section class="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-semibold">Cerrar ausencia</h2><form method="POST" action="{{ route('reemplazos.absences.close',$ausencia) }}" class="mt-3">@csrf<textarea name="motivo" required maxlength="5000" rows="3" class="w-full rounded border-amber-300" placeholder="Motivo u observación de cierre"></textarea><button class="mt-3 rounded bg-amber-700 px-4 py-2 text-sm font-semibold text-white" onclick="return confirm('¿Confirma el cierre de esta ausencia?')">Cerrar ausencia</button></form></section>@endif
</div></div>
</x-app-layout>
