<x-app-layout>
    @php
        $revision = $tramite->revisionReemplazo;
        $pendingDocuments = $requisitosDocumentales->contains(fn ($item) => $item->obligatorio && ! $item->cumplido);
        $configurationIssues = collect([
            $clasificaciones->isEmpty() ? 'falta configurar la clasificación de área' : null,
            $pendingDocuments ? 'faltan requisitos documentales obligatorios' : null,
        ])->filter();
        $formatDateTime = fn ($date) => $date?->locale('es')->isoFormat('D MMM. YYYY, HH:mm');
        $historyLabels = ['TRAMITE_CREADO' => 'Solicitud creada', 'ENVIAR_A_GESTION_PERSONAS' => 'Solicitud enviada a Gestión de Personas', 'INICIAR_REVISION' => 'Revisión iniciada', 'REEMPLAZO_REVISION_ACTUALIZADA' => 'Avance de revisión guardado', 'DEVOLVER_CORRECCION' => 'Solicitud devuelta para corrección'];
    @endphp

    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8"><x-flash-toast />
        <header class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm text-slate-500">Bandeja de solicitudes / Solicitud de Reemplazo / Revisión</p><div class="mt-3 flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-semibold text-slate-900">Revisión de Solicitud de Reemplazo</h1><p class="mt-1 font-mono text-sm text-slate-600">{{ $tramite->codigo }}</p><p class="mt-2 text-sm text-slate-600">{{ $tramite->unidadServicio->nombre }} · Creada por {{ $tramite->creador?->name ?? 'Usuario no disponible' }}</p></div><x-status-badge :estado="$tramite->estadoTramite" /></div><a href="{{ route('gestion-personas.bandeja') }}" class="mt-5 inline-block text-sm font-semibold text-indigo-700 hover:text-indigo-900">← Volver a Bandeja de solicitudes</a></header>
        <section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><ol class="grid gap-3 text-sm sm:grid-cols-4"><li class="flex items-center gap-2 font-medium text-emerald-800"><span class="grid h-6 w-6 place-items-center rounded-full border border-current">✓</span>Solicitud creada</li><li class="flex items-center gap-2 font-semibold text-blue-800"><span class="grid h-6 w-6 place-items-center rounded-full border border-current">2</span>Revisión de Gestión de Personas</li><li class="flex items-center gap-2 text-slate-400"><span class="grid h-6 w-6 place-items-center rounded-full border border-current">3</span>Documento generado</li><li class="flex items-center gap-2 text-slate-400"><span class="grid h-6 w-6 place-items-center rounded-full border border-current">4</span>Finalizada</li></ol></section>

        <div class="grid grid-cols-1 items-start gap-6 xl:grid-cols-12"><main class="space-y-6 xl:col-span-7">
            @include('reemplazos._detail')
            <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Periodos de la solicitud</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><p class="text-sm font-semibold">Ausencia del funcionario</p><p>{{ $tramite->reemplazo->ausencia?->fecha_inicio?->format('d-m-Y') ?? '—' }} al {{ $tramite->reemplazo->ausencia?->fecha_termino?->format('d-m-Y') ?? '—' }}</p><p class="text-sm text-slate-500">{{ $tramite->reemplazo->ausencia?->fecha_inicio && $tramite->reemplazo->ausencia?->fecha_termino ? $tramite->reemplazo->ausencia->fecha_inicio->diffInDays($tramite->reemplazo->ausencia->fecha_termino)+1 : 0 }} días calendario</p></div><div><p class="text-sm font-semibold">Cobertura de este reemplazante</p><p>{{ $tramite->reemplazo->fecha_inicio?->format('d-m-Y') ?? '—' }} al {{ $tramite->reemplazo->fecha_termino?->format('d-m-Y') ?? '—' }}</p><p class="text-sm text-slate-500">{{ $tramite->reemplazo->dias_calendario }} días calendario</p></div></div>@if($tramite->reemplazo->ausencia?->coberturas?->count()>1)<div class="mt-4 border-t pt-4"><h3 class="text-sm font-semibold">Otras coberturas asociadas</h3>@foreach($tramite->reemplazo->ausencia->coberturas->where('id','!=',$tramite->reemplazo->id) as $coverage)<p class="mt-1 text-sm">{{ $coverage->reemplazante?->nombre_completo ?? 'Reemplazante pendiente' }} · {{ $coverage->fecha_inicio?->format('d-m-Y') ?? '—' }} al {{ $coverage->fecha_termino?->format('d-m-Y') ?? '—' }} · {{ $coverage->tramite->estadoTramite->nombre }}</p>@endforeach</div>@endif</section>
            <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold text-slate-900">Documentos de respaldo</h2><div class="mt-4 space-y-3">@forelse($tramite->adjuntos as $adjunto)<article class="flex flex-wrap justify-between gap-4 rounded-lg border border-slate-200 p-4"><div><p class="font-medium text-slate-900">{{ $adjunto->original_name }}</p><p class="mt-1 text-sm text-slate-600">{{ $adjunto->tipoDocumento?->nombre ?? 'Sin tipo documental' }} · Versión {{ $adjunto->version }} · {{ $adjunto->status }}</p><p class="mt-1 text-xs text-slate-500">Cargado por {{ $adjunto->cargadoPor?->name ?? 'Usuario no disponible' }} · {{ $formatDateTime($adjunto->created_at) }}</p></div>@can('tramites.adjuntos.descargar')<a href="{{ route('tramites.adjuntos.download', [$tramite, $adjunto]) }}" class="text-sm font-semibold text-indigo-700">Descargar</a>@endcan</article>@empty<p class="text-sm text-slate-500">Aún no hay documentos adjuntos.</p>@endforelse</div></section>
            <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold text-slate-900">Historial relevante</h2><ol class="mt-4 space-y-4">@foreach($tramite->historial as $event)<li class="border-l-2 border-blue-200 pl-4"><p class="font-medium text-slate-900">{{ $historyLabels[$event->action_code] ?? str_replace('_', ' ', ucwords(strtolower($event->action_code), '_')) }}</p><p class="text-sm text-slate-600">{{ $event->usuario?->name ?? 'Sistema' }} · {{ $formatDateTime($event->occurred_at) }}</p>@if($event->observation)<p class="mt-1 text-sm text-slate-700">{{ $event->observation }}</p>@endif</li>@endforeach</ol></section>
        </main>
        <aside class="xl:col-span-5"><section x-data="replacementReview({ grado: @js(old('grado_eus_informado', $revision?->grado_eus_informado)), clasificacion: @js(old('clasificacion_area_id', $revision?->clasificacion_area_id)), normativa: @js(old('cumple_normativa', $revision?->cumple_normativa)), approvable: @js($tramite->estadoTramite->codigo === 'EN_REVISION' && auth()->user()->can('reemplazos.revisar_personal')), documentsReady: @js(! $pendingDocuments) })" class="rounded-xl border border-indigo-100 bg-indigo-50 p-5 shadow-sm xl:sticky xl:top-20 xl:max-h-[calc(100vh-6rem)] xl:overflow-y-auto"><h2 class="font-semibold text-slate-900">Revisión administrativa</h2><p class="mt-1 text-sm text-slate-600">Guarda los datos ingresados sin finalizar la revisión.</p>
            @if($errors->any())<div class="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><p class="font-semibold">Revisa los antecedentes pendientes:</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div x-show="approvalError" x-cloak class="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert"><p x-text="approvalError"></p><a x-show="recoveryUrl" :href="recoveryUrl" class="mt-2 inline-block font-semibold underline">Ir al detalle y reintentar</a></div>
            <form x-ref="revisionForm" id="revision-form" method="POST" action="{{ route('reemplazos.review.save', $tramite) }}" @submit="saving = true" class="mt-5 space-y-5">@csrf @method('PUT')
                <div><label for="grado_eus_informado" class="block text-sm font-medium text-slate-800">Último grado E.U.S.</label><div class="mt-1 flex rounded-md shadow-sm"><input x-model.number="grado" id="grado_eus_informado" name="grado_eus_informado" type="number" min="1" step="1" inputmode="numeric" placeholder="Ej.: 15" value="{{ old('grado_eus_informado', $revision?->grado_eus_informado) }}" class="min-w-0 flex-1 rounded-l-md border-slate-300"><span class="inline-flex items-center rounded-r-md border border-l-0 border-slate-300 bg-slate-100 px-3 text-sm text-slate-600">° E.U.S.</span></div><template x-if="fieldErrors.grado_eus_informado"><p class="mt-1 text-sm text-red-700" x-text="fieldErrors.grado_eus_informado[0]"></p></template></div>
                <div><label for="clasificacion_area_id" class="block text-sm font-medium text-slate-800">Clasificación de área</label>@if($clasificaciones->isEmpty())<p class="mt-1 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">No existen clasificaciones de área activas configuradas.</p>@else<select x-model.number="clasificacion" id="clasificacion_area_id" name="clasificacion_area_id" class="mt-1 w-full rounded-md border-slate-300"><option value="">Seleccione una clasificación</option>@foreach($clasificaciones as $clasificacion)<option value="{{ $clasificacion->id }}" @selected((string) old('clasificacion_area_id', $revision?->clasificacion_area_id) === (string) $clasificacion->id)>{{ $clasificacion->nombre }}</option>@endforeach</select><template x-if="fieldErrors.clasificacion_area_id"><p class="mt-1 text-sm text-red-700" x-text="fieldErrors.clasificacion_area_id[0]"></p></template>@endif</div>
                <fieldset><legend class="text-sm font-medium text-slate-800">Cumplimiento de normativa</legend><div class="mt-2 flex flex-wrap gap-4"><label class="flex items-center gap-2 text-sm"><input x-model.number="normativa" type="radio" name="cumple_normativa" value="1" @checked((string) old('cumple_normativa', $revision?->cumple_normativa) === '1')> Cumple</label><label class="flex items-center gap-2 text-sm"><input x-model.number="normativa" type="radio" name="cumple_normativa" value="0" @checked((string) old('cumple_normativa', $revision?->cumple_normativa) === '0')> No cumple</label></div><template x-if="fieldErrors.cumple_normativa"><p class="mt-1 text-sm text-red-700" x-text="fieldErrors.cumple_normativa[0]"></p></template></fieldset>
            </form>
            <div class="mt-5 border-t border-indigo-200 pt-4"><h3 class="text-sm font-semibold text-slate-800">Requisitos documentales</h3><div class="mt-2 space-y-2 text-sm">@forelse($requisitosDocumentales as $item)<div class="flex items-center justify-between gap-3 rounded-lg bg-white/70 p-3"><span>{{ $item->nombre }}</span><span class="rounded-full px-2.5 py-1 text-xs font-medium {{ $item->cumplido ? 'bg-emerald-100 text-emerald-800' : ($item->obligatorio ? 'bg-amber-100 text-amber-900' : 'bg-slate-200 text-slate-700') }}">{{ $item->cumplido ? 'Cumplido' : ($item->obligatorio ? 'Pendiente' : 'Opcional') }}</span></div>@empty<p class="text-sm text-slate-600">No hay requisitos documentales configurados para esta solicitud.</p>@endforelse</div></div>
            <p class="mt-4 text-xs text-slate-600">{{ $revision?->updated_at ? 'Último guardado: '.$formatDateTime($revision->updated_at) : 'Aún no hay avance guardado.' }}</p>
            @if($configurationIssues->isNotEmpty())<p class="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">No puedes aprobar: {{ $configurationIssues->implode('; ') }}.</p>@endif
            <p x-show="missingApprovalFields.length" x-cloak class="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">No puedes aprobar: <span x-text="missingApprovalFields.join('; ')"></span>.</p>
            <div class="mt-5 border-t border-indigo-200 pt-4"><div class="grid gap-3 sm:grid-cols-2"><button form="revision-form" type="submit" name="accion" value="guardar" :disabled="saving || approving" class="w-full rounded-md border border-indigo-300 bg-white px-4 py-2 text-sm font-semibold text-indigo-800 disabled:cursor-not-allowed disabled:opacity-50"><span x-show="!saving">Guardar avance</span><span x-show="saving">Guardando…</span></button><button type="button" @click="openApproval()" :disabled="saving || approving || !approvable" class="w-full cursor-pointer rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Aprobar antecedentes</button></div><button type="button" @click="returnOpen = true" :disabled="saving || approving" class="mt-3 w-full rounded-md border border-amber-300 px-4 py-2 text-sm font-semibold text-amber-800 hover:bg-amber-50 disabled:cursor-not-allowed disabled:opacity-50">Devolver para corrección</button></div>
            <div x-cloak x-show="approvalOpen" role="dialog" aria-modal="true" aria-labelledby="approval-title" class="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-4"><div class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl" @click.outside="if (!approving) approvalOpen = false"><h3 id="approval-title" class="text-lg font-semibold">Aprobar antecedentes</h3><p class="mt-2 text-sm text-slate-600">¿Confirmas que deseas aprobar los antecedentes y generar el documento oficial en PDF?</p><div class="mt-5 flex justify-end gap-3"><button type="button" @click="approvalOpen = false" :disabled="approving" class="rounded-md px-4 py-2 text-sm disabled:opacity-50">Cancelar</button><button type="button" @click="approve()" :disabled="approving" class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><span x-show="!approving">Sí, aprobar y generar PDF</span><span x-show="approving">Generando PDF…</span></button></div></div></div>
            <div x-cloak x-show="returnOpen" x-transition role="dialog" aria-modal="true" aria-labelledby="return-title" @keydown.escape.window="returnOpen = false" class="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-4"><div class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl" @click.outside="returnOpen = false"><h3 id="return-title" class="text-lg font-semibold text-slate-900">Devolver para corrección</h3><p class="mt-2 text-sm text-slate-600">Guarda el avance antes de devolver para conservar los cambios no guardados. La Jefatura deberá corregir los antecedentes antes de reenviar.</p><form method="POST" action="{{ route('reemplazos.return', $tramite) }}" class="mt-4">@csrf<label for="observation" class="block text-sm font-medium text-slate-800">Observación para Jefatura</label><textarea id="observation" name="observation" required maxlength="5000" class="mt-1 w-full rounded-md border-slate-300" rows="5">{{ old('observation') }}</textarea><div class="mt-5 flex justify-end gap-3"><button type="button" @click="returnOpen = false" class="rounded-md px-4 py-2 text-sm">Cancelar</button><x-primary-button>Confirmar devolución</x-primary-button></div></form></div></div>
        </section></aside></div>
    </div></div>
</x-app-layout>
